name: Compile CV to PDF

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install Pandoc and WeasyPrint
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc weasyprint

      - name: Build Styled PDF
        run: |
          pandoc cv.md -o cv.pdf \
            --pdf-engine=weasyprint \
            --css=style.css \
            --standalone

      - name: Upload PDF Artifact
        uses: actions/upload-artifact@v4
        with:
          name: CV-PDF
          path: cv.pdf
